---

- name: "php-fpm:config:master:includes:add | Add include-statements to master configuration."
  lineinfile:
    dest:  "{{ item.0.path }}"
    state: "present"
    line:  "include = {{ item.1 }}"
    insertafter: "EOF"
  with_subelements:
     - php_fpm_master_configs
     - includes
  changed_when: '{{ "include = " + item.1 not in php_fpm_master_configs_includes.results|selectattr("item", "equalto", item.0.path)|map(attribute="stdout_lines")|list|first }}'
  notify:
    - "service:php-fpm:reload"
