---

- name: "php-fpm:config:master:includes:add | Add include-statements to master configuration."
  lineinfile:
    dest:  "{{ php_fpm_master_config_path }}"
    state: "present"
    line:  "include = {{ item }}"
    insertafter: "EOF"
  with_items:
    - '{{ php_fpm_pools|rejectattr("enabled", "sameas", false)|rejectattr("path", "none")|map(attribute="path")|list }}'
  changed_when: 'item not in php_fpm_config_old_includes'
  notify:
    - "service:php-fpm:reload"
