---

- command: 'grep include {{ item }}'
  with_items:
    - '{{ php_fpm_master_configs|rejectattr("enabled", "sameas", false)|rejectattr("path", "none")|map(attribute="path")|list }}'
  register: php_fpm_master_configs_includes
  changed_when: false
  ignore_errors: true
