---

- name: "php-fpm:config:master:includes:remove | Remove include-statements from master configuration."
  lineinfile:
    dest:  '{{ item.0.item }}'
    state: "absent"
    line:  '{{ item.1 }}'
  with_subelements:
     - php_fpm_master_configs_includes.results
     - stdout_lines
  changed_when: false
  failed_when:  false
  notify:
    - "service:php-fpm:reload"
