---

- name: "php-fpm:config:master:update | Update master configurations"
  ini_file:
    backup:  "no"
    state:   "present"
    dest:    "{{ item.path }}"
    section: "{{ item.section }}"
    option:  "{{ item.option }}"
    value:   "{{ item.value }}"
  with_ini_configs:
    - '{{ php_fpm_master_configs }}'
  notify:
    - "service:php-fpm:reload"
