---

- name: "php-fpm:config:pools:clear | Clear pool all pool configurations without 'merge: true'."
  file:
    path:  "{{ item }}"
    state: "absent"
  changed_when: false
  with_items:
     - '{{ php_fpm_pools | default([]) | rejectattr("merge", "sameas", true) | list | map(attribute="path") | list }}'
