---

- name: "php-fpm:create:default:directories | Ensure default directories."
  file:
    path:  '{{ item.dir }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode:  '{{ item.mode }}'
    state: directory
  with_items:
    - '{"dir": "{{php_fpm_defaults_path_pools_available }}", "owner": "{{ php_fpm_defaults_pool_directory_owner }}", "group": "{{ php_fpm_defaults_pool_directory_group }}", "mode": "{{ php_fpm_defaults_pool_directory_mode }}"}'
    - '{"dir": "{{php_fpm_defaults_path_pools_enabled }}", "owner": "{{ php_fpm_defaults_pool_directory_owner }}", "group": "{{ php_fpm_defaults_pool_directory_group }}", "mode": "{{ php_fpm_defaults_pool_directory_mode }}"}'
